### ISSUE TITLE
"Object reference not set to an instance of an object."

### ISSUE THREAD

**Issue by karmacon** [fanyangxi/log4net.Appender.LiteDB#1]
I installed the Nuget package and copied the configuration sample into my app.config file. I also added an appender reference. 

        <root>
            <appender-ref ref="LiteDbAppender"/>
        </root>

When I run the app I get this error:

> "Object reference not set to an instance of an object."
> "   at log4net.Appender.LiteDB.LiteAppender.GetCollection()"

Is there anything that needs to be done in the code to get this library to work?
Log4net and LiteDB are both installed and working properly.

**Comment by fanyangxi** [comment]
Hi @karmacon, 

This error might be caused by the wrong configuration I put in the README.md.

Please refer to this issue #2 
I have fixed the README, should be ok if you're using the new configuration sample.
